name: Plan Infrastructure
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      role-session-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: ${{ inputs.role-session-name }}
          aws-region: ${{ inputs.aws-region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9

      - name: Run terraform fmt check
        id: fmt
        run: terraform fmt -check -diff -recursive .
        working-directory: ./${{ inputs.working-directory }}

      - name: Initialize Terraform
        id: init
        working-directory: ./${{ inputs.working-directory }}
        run: |
          terraform init -input=false

      - name: Validate Terraform
        id: validate
        working-directory: ./${{ inputs.working-directory }}
        run: |
          terraform validate

      - name: Plan Terraform
        id: plan
        working-directory: ./${{ inputs.working-directory }}
        run: |
          terraform plan -input=false
